### ISSUE TITLE
Error: magic.MagicException: b'could not find any magic files!'

### ISSUE THREAD

**Issue by maphew** [calpaterson/dircast#5]
_(I'm creating a fair bit of noise. Please let me know if this is unwelcome and I'll track my activity on this somewhere else. Github doesn't let me put Issues on my own fork (or I haven't seen how anyway.)_

This exception is particular to Windows, due to binary dependency _file.exe_.  

```
> dircast --debug "8 Fold Path Edmonton 2013"
INFO:dircast.cli:started
INFO:dircast.files:loading 8 Fold Path Edmonton 2013\channel.yml
INFO:dircast.files:checking 8 Fold Path Edmonton 2013\2013-02-21-Right View.mp3
Traceback (most recent call last):
  File "C:\Python34\Scripts\dircast-script.py", line 9, in <module>
    load_entry_point('dircast==0.0', 'console_scripts', 'dircast')()
  File "C:\Python34\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python34\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "C:\Python34\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python34\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "d:\code\dircast\dircast\cli.py", line 22, in main
    find_files(channel_dict["url"], Path(directory)))
  File "d:\code\dircast\dircast\files.py", line 73, in find_files
    mimetype = guess_mimetype(child)
  File "d:\code\dircast\dircast\files.py", line 32, in guess_mimetype
    magic_mimetype = magic.from_file(str(path), mime=True)
  File "C:\Python34\lib\site-packages\magic.py", line 128, in from_file
    m = _get_magic_type(mime)
  File "C:\Python34\lib\site-packages\magic.py", line 116, in _get_magic_type
    i = _instances[mime] = Magic(mime=mime)
  File "C:\Python34\lib\site-packages\magic.py", line 67, in __init__
    magic_load(self.cookie, magic_file)
  File "C:\Python34\lib\site-packages\magic.py", line 246, in magic_load
    return _magic_load(cookie, coerce_filename(filename))
  File "C:\Python34\lib\site-packages\magic.py", line 185, in errorcheck_negative_one
    raise MagicException(err)
magic.MagicException: b'could not find any magic files!'
```

**Comment by maphew** [comment]
Cure is to set MAGIC path variable

```
set MAGIC="C:\path\to\GnuWin32\share\misc\magic"
```

**Comment by calpaterson** [comment]
Noise is definitely not unwelcome :)  I'm going to reopen this one because it would help people to have this variable documented in the README
