### ISSUE TITLE
ValueError 'folder\\file.mp3' does not start with 'folder\\file.mp3\\folder\\file'

### ISSUE THREAD

**Issue by maphew** [calpaterson/dircast#6]
Seems to be some unwanted recursion in get_file_metadata() 

```
> dircast "8 Fold Path Edmonton 2013"
Traceback (most recent call last):
  File "C:\Python34\Scripts\dircast-script.py", line 9, in <module>
    load_entry_point('dircast==0.0', 'console_scripts', 'dircast')()
  File "C:\Python34\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python34\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "C:\Python34\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python34\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "d:\code\dircast\dircast\cli.py", line 22, in main
    find_files(channel_dict["url"], Path(directory)))
  File "d:\code\dircast\dircast\files.py", line 83, in find_files
    files.append(get_file_metadata(channel_url, mimetype, child))
  File "d:\code\dircast\dircast\files.py", line 60, in get_file_metadata
    str(path.relative_to(path, path.parents[0])),
  File "C:\Python34\lib\pathlib.py", line 806, in relative_to
    .format(str(self), str(formatted)))
ValueError: '8 Fold Path Edmonton 2013\\2013-02-21-Right View.mp3' does not start with '8 Fold Path Edmonton 2013\\2013-02-21-Right View.mp3\\8 Fold Path Edmonton 2013'
```

**Comment by maphew** [comment]
Work around is to use a fully qualified path, `dircast "X:\path\to\folder"`. 
Windows shortcut for where you're sitting is to use %cd%:

```
dircast "%cd%\8 Fold Path Edmonton 2013"
```

**Comment by calpaterson** [comment]
I think this bug is something to do with inadvertently using the current directory.  For example:

```
(dircast) cpaterson@youview-1 ~/s/dircast> dircast --debug tests/test_data/0/
INFO:dircast.cli:started
INFO:dircast.files:loading tests/test_data/0/channel.yml
INFO:dircast.files:checking tests/test_data/0/1-some-silence.mp3
INFO:dircast.files:tests/test_data/0/1-some-silence.mp3 is of type audio/mpeg - is audio
Traceback (most recent call last):
  File "/home/cpaterson/.virtualenvs/dircast/bin/dircast", line 9, in <module>
    load_entry_point('dircast==0.0', 'console_scripts', 'dircast')()
  File "/home/cpaterson/.virtualenvs/dircast/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/cpaterson/.virtualenvs/dircast/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/cpaterson/.virtualenvs/dircast/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cpaterson/.virtualenvs/dircast/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/cpaterson/src/dircast/dircast/cli.py", line 22, in main
    find_files(channel_dict["url"], Path(directory)))
  File "/home/cpaterson/src/dircast/dircast/files.py", line 83, in find_files
    files.append(get_file_metadata(channel_url, mimetype, child))
  File "/home/cpaterson/src/dircast/dircast/files.py", line 60, in get_file_metadata
    str(path.relative_to(path, path.parents[0])),
  File "/usr/lib64/python3.4/pathlib.py", line 802, in relative_to
    .format(str(self), str(formatted)))
ValueError: 'tests/test_data/0/1-some-silence.mp3' does not start with 'tests/test_data/0/1-some-silence.mp3/tests/test_data/0'
```

where it fails, but:

```
(dircast) cpaterson@youview-1 ~/s/dircast> cd tests/test_data/0/
(dircast) cpaterson@youview-1 ~/s/d/t/t/0> dircast --debug .
INFO:dircast.cli:started
INFO:dircast.files:loading channel.yml
INFO:dircast.files:checking 1-some-silence.mp3
INFO:dircast.files:1-some-silence.mp3 is of type audio/mpeg - is audio
INFO:dircast.files:checking 2-some-silence.mp3
INFO:dircast.files:2-some-silence.mp3 is of type audio/mpeg - is audio
INFO:dircast.files:checking 3-some-silence.mp3
INFO:dircast.files:3-some-silence.mp3 is of type audio/mpeg - is audio
INFO:dircast.files:checking channel.yml
INFO:dircast.files:channel.yml is of type text/plain - not audio
<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">
  <channel>
    <title>All About Everything</title>
    <link>http://www.example.com/podcasts/everything/index.html</link>
    <description>A show about everything</description>
    <atom:link href="http://www.example.com/podcasts/everything/index.html" rel="self"/>
    <docs>http://www.rssboard.org/rss-specification</docs>
    <generator>python-feedgen</generator>
    <lastBuildDate>Wed, 22 Jun 2016 11:17:15 +0000</lastBuildDate>
    <item>
      <title>Some silence</title>
      <guid isPermaLink="false">7a37534b4994869e96552561449b2f5b9ddd985e</guid>
      <enclosure url="http://www.example.com/podcasts/everything/index.html." length="17870" type="audio/mpeg"/>
      <itunes:duration>00:00:01</itunes:duration>
    </item>
    <item>
      <title>More silence</title>
      <guid isPermaLink="false">9372569d966cdd83f6e7f0b0bc5ea5f3e1cf57f5</guid>
      <enclosure url="http://www.example.com/podcasts/everything/index.html." length="17870" type="audio/mpeg"/>
      <itunes:duration>00:00:01</itunes:duration>
    </item>
    <item>
      <title>Even more silence</title>
      <guid isPermaLink="false">8cc785ada8f6e63c1c0874e4ba8d809a7848cebe</guid>
      <enclosure url="http://www.example.com/podcasts/everything/index.html." length="17870" type="audio/mpeg"/>
      <itunes:duration>00:00:01</itunes:duration>
    </item>
  </channel>
</rss>
```

**Comment by calpaterson** [comment]
Or rather, not with the current directory, but with the path logic in general.  I'm having a little trouble replicating it in a test

**Comment by maphew** [comment]
So cd0fe94  doesn't fix 6, invocation with current directory (`dircast .`), but I don't really get how `path` is constructed and used in files.py. It's an object with attributes and not a string, but I don't see where/how it's created (yet). 

In any case my hunch is _posixpath_ module is on the right path [heheh] to a solution.

**Comment by maphew** [comment]
Ok, I figured out where the 'path' object is constructed (cli.py, find_files())  and in reading up on pathlib I thought using PurePath would be better than posixpath, they're probably both using the same core underneath, but I couldn't make PurePath work with the same simplicity and cleanness. (Probably as much a reflection of my small programming skills as anything else!)

In any case posix was not the solution here, but chasing that fish did get me into the right spot: resolve the actual path at the beginning of find_files(). 

I don't know if this will give the same url path for the rss file with symlinks, not tested.
